---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: net-attributes
    run_list: recipe[udev::net]
    attributes:
      udev:
        net:
          eth0: 08:00:27:f9:09:1f
  - name: net-data-bags
    run_list: recipe[udev::net]
    data_bag_path: "test/integration/net-data-bags/data_bags"
